services:
    nginx:
        container_name: 
            nginx
        build:
            context: ./requirements/nginx
        env_file:
            - .env
        ports:
            - "${NGINX_PORT}:4343"
        restart: 
            always
        networks:
            - inception
        volumes:
            - nginx_data:/var/www/html

volumes:
  nginx_data:
  #- ./requirements/nginx/html:/var/www/html


networks:
    inception:
        driver: bridge
        