version: "3.8"

services:
  mariadb:
    image: inception_mariadb
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - inception
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      DB_ADMIN_USER: "${DB_ADMIN_USER}"
      DB_ADMIN_PASSWORD_FILE: /run/secrets/db_admin_password
    secrets:
      - db_root_password
      - mysql_password
      - db_admin_password
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    image: inception_wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    environment:
      WORDPRESS_TITLE: "${WORDPRESS_TITLE}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      DB_ADMIN_USER: "${DB_ADMIN_USER}"
      DB_ADMIN_EMAIL: "${DB_ADMIN_EMAIL}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_USER_EMAIL: "${MYSQL_USER_EMAIL}"
      DOMAIN_NAME: "${DOMAIN_NAME}"
    secrets:
      - db_admin_password
      - mysql_password
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    image: inception_nginx
    ports:
      - "${NGINX_PORT}:443"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - wordpress
    networks:
      - inception
    secrets:
      - tls_cert
      - tls_key
    volumes:
      - wordpress_data:/var/www/html   # serve WordPress files
      

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  mysql_password:
    file: ../secrets/mysql_password.txt
  db_admin_password:
    file: ../secrets/db_admin_password.txt
  tls_cert:
    file: ../secrets/tls_cert.pem
  tls_key:
    file: ../secrets/tls_key.pem

volumes:
  mariadb_data:
  wordpress_data:

networks:
    inception:
        driver: overlay
        