services:
    nginx:
        container_name: 
            nginx
        build:
            context: ./requeriments/nginx
        ports:
            - "${NGINX_PORT}:443"
        restart: 
            always
        networks:
            - inception
        volumes:
            - nginx_data:/var/www/html

volumes:
    nginx_data:

networks:
    inception:
        driver: bridge
        