services:
  mariadb:
    container_name: 
      mariadb
    build: ./requirements/mariadb
    ports:
      - "${MARIADB_PORT}:3306" #"<host_port>:<container_port>"
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
#   wordpress:
#     container_name: 
#       wordpress
#     build: ./requirements/wordpress
#     expose:
#     - "${WORDPRESS_PORT}:9000"
#     depends_on:
#     - mariadb
#     networks:
#     - inception
#     volumes:
#     - wordpress_data:/var/www/html

  nginx:
    container_name: 
      nginx
    build:
      context: ./requirements/nginx
    ports:
      - "${NGINX_PORT}:443" #"<host_port>:<container_port>"
    restart: 
      always
    networks:
      - inception


volumes:
  wordpress_data:
  mariadb_data:

networks:
    inception:
        driver: bridge
        